uc-cdis/tube

- LICENSE
- NOTICE
Added `LICENSE` & `NOTICE` files for `gh-audit`.
> fix(LICENSE): add missing LICENSE & NOTICE

- run_import.py
- tube/importers/sql_to_hdfs.py
> feat(sqoop): use “import-all-tables”

- tube/spark/translator.py
> fix(parser): fix text parser

- tests/gen3/tube/etlMapping.yaml
- tests/test_es/test_es.py
- tube/mappings/etl.yaml
- tube/settings.py
> fix(unittest): fix unit-test for file index

- tests/test_es/test_es.py
- tube/spark/es_writer.py
- Implemented Versioning for the Index
- You may need to change the config map to use the new mapping file if the commons still use the old version of mapping file.
> TB25: feat(version) - index versioning

- requirements.txt
Update latest version of gdcdatamodel that fixes subgroup nested
- Update latest version of gdcdatamodel that fixes subgroup nested
> fix(gdcdatamodel): update new version

- tests/gen3/tube/etlMapping.yaml
- tube/mappings/etl.yaml
- tube/spark/indexers/aggregator/nodes/direct_node.py
- tube/spark/indexers/aggregator/parser.py
- tube/spark/indexers/aggregator/translator.py
- tube/spark/indexers/base/lambdas.py
- tube/spark/indexers/base/prop.py
- tube/spark/indexers/base/translator.py
- tube/spark/indexers/collector/parser.py
- tube/utils.py
adding ordering and take the first element from the list when exist many-to-one relationship in flatten_props
- Implemented ordering and get first element of flatten_props (support many-to-one)
- Support working with many-to-one relationship
> feat(order): ordering when exist many_to_one

- tube/spark/indexers/collector/translator.py
- Default empty dataset when no data in database
> fix(empty): fix empty dataset

- tube/spark/indexers/base/lambdas.py
> fix(list_type): fix list type

- run_etl.py
- tests/test_es/test_es.py
- tube/etl/__init__.py
- tube/etl/indexers/interpreter.py
- tube/etl/outputs/es/timestamp.py
- tube/etl/outputs/es/versioning.py
There is a bug in timestamp feature branch that used hard-code index name called `etl`. It is fixed by this branch
> fix(integration): fix error getting index name

- requirements.txt
- tests/gen3/tube/etlMapping.yaml
- tube/config_helper.py
- tube/etl/indexers/aggregation/lambdas.py
- tube/etl/indexers/aggregation/nodes/direct_node.py
- tube/etl/indexers/aggregation/nodes/joining_node.py
- tube/etl/indexers/aggregation/parser.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/base/prop.py
- tube/etl/indexers/base/translator.py
- tube/etl/indexers/injection/nodes/collecting_node.py
- tube/etl/indexers/injection/parser.py
- tube/etl/indexers/injection/translator.py
- tube/etl/indexers/interpreter.py
- tube/etl/outputs/es/writer.py
- tube/mappings/etl.yaml
- tube/utils/dd.py
- tube/utils/spark.py
> feat(facet): facet in etl

- tube/etl/indexers/injection/translator.py
Fix joining and union file tables.
> fix(join): fix joining files

- run_etl.py
Forced running etl without new data
- Forced running etl without new data
> feat(force): forced running etl with no new data

- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/etl/indexers/base/prop.py
- tube/etl/indexers/base/translator.py
- tube/etl/indexers/injection/lambdas.py
- tube/etl/indexers/injection/parser.py
- tube/etl/indexers/injection/translator.py
- tube/etl/indexers/interpreter.py
- tube/utils/spark.py
Support one file belongs to multiple cases in file index
> feat(list-cases): support list of case_id

- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/etl/indexers/injection/lambdas.py
- tube/etl/indexers/injection/nodes/collecting_node.py
- tube/etl/indexers/injection/parser.py
- tube/etl/indexers/injection/translator.py
- tube/utils/dd.py
- File can belong to multiple cases
- File can connect directly to project, not case
- File with `case_id` null
- `data_format` and `data_type` empty
> fix(file): fix file and data_format

- tube/etl/indexers/aggregation/lambdas.py
- tube/etl/indexers/aggregation/nodes/special_node.py
- tube/etl/indexers/aggregation/parser.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/etl/indexers/injection/translator.py
Sliding window for viral per follow_up
- sliding window
- min/max aggregation
> feat(sliding): support sliding window

- requirements.txt
- tube/etl/indexers/aggregation/nodes/direct_node.py
- tube/etl/indexers/aggregation/nodes/special_node.py
- tube/etl/indexers/aggregation/parser.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/base/prop.py
- tube/etl/indexers/base/translator.py
- tube/etl/indexers/injection/parser.py
- tube/etl/indexers/interpreter.py
> feat(join_no_agg): joining without aggregate

- tube/etl/indexers/injection/translator.py
fix https://github.com/uc-cdis/tube/pull/69/files introduced a bug that overwrite the root df for each child df to join
> fix(child_dfs): do not overwrite root df

- run_etl.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/injection/parser.py
- tube/etl/indexers/injection/translator.py
final fix for file index without links to subject
> fix(bug): bug when removing injecting

- tube/etl/plugins/post_process.py
Support legacy format if tube can not map `auth_resource_path`
> fix(legacy_support): legacy support if can not find resource path in user.yaml

- tests/gen3/tube/user.yaml
- tube/etl/plugins/post_process.py
Replace "rbac" with "authz" in useryaml
> Replace rbac with authz in useryaml

- tube/utils/general.py
fixing auth_resource_path following the old logic
> fix(resource_path): fix resource path

- tube/etl/indexers/injection/translator.py
Feature:
- Perform aggregation for all root properties in file index with the default `set` function
> fix(inject): add default aggregation fn

- tube/etl/indexers/aggregation/parser.py
- tube/etl/indexers/aggregation/translator.py
- Fix unnecessary `project_id` property
> fix(project): exception for project_id

- tube/etl/indexers/aggregation/nodes/aggregated_node.py
- tube/etl/indexers/injection/parser.py
- Fix NoneType bug in injection parser
> fix(injection): fix parser

- tube/etl/indexers/injection/translator.py
> fix(project_id): fix joining node upper subject

- tube/etl/indexers/base/parser.py
- tube/etl/indexers/base/translator.py
- tube/etl/indexers/injection/translator.py
> fix(type): add type for project_id and fix update_type func

- tube/etl/indexers/injection/parser.py
- tube/etl/outputs/es/versioning.py
- tube/etl/outputs/es/writer.py
Jira Ticket: [PXP-5990](https://ctds-planx.atlassian.net/browse/PXP-5990)
- Don't do backup
> fix(versioning): no backup

- tube/etl/indexers/injection/parser.py
- Fix small issue of missing injecting_props in some commons. Which can lead to an empty file index
> fix(props): no injecting_props

- tube/etl/indexers/base/parser.py
- tube/etl/indexers/base/prop.py
- tube/etl/indexers/injection/translator.py
Jira Ticket: [PXP-6597](https://ctds-planx.atlassian.net/browse/PXP-6597)
- Include source node name into the index
> feat(node_name): add node_name field

- tube/etl/indexers/base/lambdas.py
Fix tube to adapt with field having array type in postgresql
- Support array type field in postgresql
> fix(list): fix array type

- README.md
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> Update README.md collector index

- Dockerfile
- tube/etl/indexers/base/parser.py
Fix bug where whitespace is unintentionally left in name
> fix parser

- tube/etl/indexers/aggregation/nodes/parent_node.py
- tube/etl/indexers/aggregation/nodes/special_node.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/base/translator.py
- tube/utils/spark.py
Jira Ticket: [PXP-7229](https://ctds-planx.atlassian.net/browse/PXP-7229)
wholeTextFiles function cause OOM issue. We avoid that by using textFile
> fix(oom): not use wholetextfiles

- tube/etl/indexers/aggregation/nodes/joining_node.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/mappings/etl.yaml
Jira Ticket: [PXP-8509](https://ctds-planx.atlassian.net/browse/PXP-8509)
Multiple field for joining two indices
> feat(multi): multiple field join

- README.md
- requirements.txt
- tests/test_db/test_db.py
- tube/importers/sql_to_hdfs.py
- tube/settings.py
- tube/utils/db.py
- tube/utils/spark.py
* Tube support for PostgreSQL SSL
* Bug fix for `Cannot run multiple SparkContexts at once` error when starting up `tube`.
* Update Readme and test suite to cover using PostgreSQL with SSL
* Update `python` dependencies for `gdcdictionary` and `py2neo`.
> Update Tube for PostgreSQL ssl support

- .secrets.baseline
- tests/gen3/tube/etlMapping.yaml
- tube/etl/indexers/aggregation/lambdas.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/etl/indexers/injection/lambdas.py
- tube/etl/indexers/injection/translator.py
Jira Ticket: [PXP-8848](https://ctds-planx.atlassian.net/browse/PXP-8848)
- Support one node has multiple parents
> fix(duplication): fix duplicates with parent node

- tube/etl/outputs/es/writer.py
Jira Ticket: [PXP-9112](https://ctds-planx.atlassian.net/browse/PXP-9112)
- missing multi level nested field in array_config
> fix(array): add multi-level nested field to array config

- .travis.yml
- Pipfile
- Pipfile.lock
- dev-requirements.txt
- tube/etl/indexers/aggregation/nested/parser.py
- tube/etl/indexers/aggregation/parser.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/injection/parser.py
Jira Ticket: [PXP-9267](https://ctds-planx.atlassian.net/browse/PXP-9267)
Fix bug when comparing str with None Type caused by null value in join_on field
> fix(joining): fix joining props error

- .travis.yml
- Pipfile
- tube/etl/indexers/injection/translator.py
- Fixing issue of missing _file_id in injection/collector index
> fix(file_id): fix missing file_id

- tube/etl/indexers/aggregation/nested/parser.py
- tube/etl/indexers/aggregation/parser.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/lambdas.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/injection/parser.py
- tube/etl/indexers/injection/translator.py
- tube/etl/outputs/es/writer.py
Jira Ticket: [PXP-9831](https://ctds-planx.atlassian.net/browse/PXP-9831)
Fixing type of fields to be number, boolean rather than only text
> fix(type): fix type for non str type

- tube/etl/indexers/base/parser.py
> fix(bool): map to string

- tube/etl/indexers/aggregation/nested/parser.py
Jira Ticket: [PXP-9952](https://ctds-planx.atlassian.net/browse/PXP-9952)
Fix to add full path for nested properties
> fix(array): fix array types

- tests/gen3/tube/creds.json
- tests/test_data/.subject-excluded.json
- tests/test_es/test_es.py
- tube/settings.py
* Added an extra test file that includes all the records that needed to be excluded for `test_get_list_from_path` and corresponding logic to fix the failing test.
> Fix broken test case

- .github/workflows/test.yaml
Change compose-etl branch to master for test
> fix(compose): change compose-etl to master

- tube/etl/indexers/aggregation/new_translator.py
- tube/etl/indexers/base/parser.py
> fix(master): fix broken master branch

- tube/etl/indexers/aggregation/new_translator.py
- tube/etl/indexers/injection/new_translator.py
- tube/etl/indexers/interpreter.py
Fix empty dataframe while building nested nodes.
> fix(empty): fix empty dataframe for nested prop

- tube/etl/indexers/aggregation/new_translator.py
Fix etl when file index is empty
> fix(joining): only join if there is not empty index

- tests/value/value.py
- tube/etl/indexers/aggregation/nested/translator.py
- tube/etl/indexers/aggregation/new_translator.py
- tube/etl/indexers/aggregation/translator.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/base/translator.py
- tube/etl/indexers/injection/new_translator.py
- tube/etl/indexers/injection/parser.py
- tube/etl/indexers/injection/translator.py
- tube/etl/indexers/interpreter.py
- tube/etl/outputs/es/timestamp.py
Jira Ticket: [PXP-10315](https://ctds-planx.atlassian.net/browse/PXP-10315)
Also write empty dataframe with full columns
> fix(dataframe): fix empty dataframe

- tube/etl/indexers/aggregation/new_translator.py
- tube/etl/indexers/base/parser.py
- tube/etl/indexers/base/translator.py
[PXP-103125](https://ctds-planx.atlassian.net/browse/PXP-10315)
> Fix get type with list

- tube/etl/indexers/aggregation/nested/translator.py
- tube/etl/indexers/aggregation/new_translator.py
- tube/etl/indexers/injection/new_translator.py
Jira Ticket: [PXP-10368](https://ctds-planx.atlassian.net/browse/PXP-10368)
> fix(array): fix to write array config

- tests/integrated_tests/gen3/tube/etlMapping.yaml
- tube/etl/indexers/aggregation/new_translator.py
- tube/etl/indexers/aggregation/nodes/parent_node.py
- tube/etl/indexers/aggregation/parser.py
- tube/etl/indexers/base/translator.py
Jira Ticket: [PXP-10516](https://ctds-planx.atlassian.net/browse/PXP-10516)
* Add the option to specify the relation type of parent nodes should be either `1-1` or `1-n`
[PXP-10516]: https://ctds-planx.atlassian.net/browse/PXP-10516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(relation): add option to indicate the relations

- tube/etl/indexers/base/logic.py
- tube/etl/indexers/base/translator.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> Remove duplicated columns id

- tube/etl/indexers/injection/new_translator.py
- tube/etl/indexers/injection/parser.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
Fix issue with the same name of non-leaf properties and leaf properties
Fix issue with the same name of non-leaf properties and leaf properties
> Fix same name issue of leaf nodes and parent nodes

- tube/etl/indexers/base/translator.py
- tube/etl/indexers/injection/new_translator.py
* Fix the case when data is array and nested in array field of file index
> flatten array list

- tube/etl/indexers/base/parser.py
Jira Ticket: [PXP-10884](https://ctds-planx.atlassian.net/browse/PXP-10884)
- Fix to get correct type of items in list type field
[PXP-10884]: https://ctds-planx.atlassian.net/browse/PXP-10884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(type): correct type of items in list

- .github/labeler.yml
- .github/workflows/labeler.yml
- README.md
Jira Ticket: [GQE-74](https://ctds-planx.atlassian.net/browse/GQE-74)
[GQE-74]: https://ctds-planx.atlassian.net/browse/GQE-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> adding labeler to tube repo

- .github/workflows/image_build_and_test.yaml
Jira Ticket: [PXP-10933](https://ctds-planx.atlassian.net/browse/PXP-10933)
- Github workflow updated to use `GITBHUB_OUTPUT`, since `set-output` is deprecated
[PXP-10933]: https://ctds-planx.atlassian.net/browse/PXP-10933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-10933 Update workflow to use GITHUB_OUTPUT

- run_etl.py
- tests/integrated_tests/test_es/test_es.py
- tests/integrated_tests/utils_es.py
- tube/etl/outputs/es/writer.py
- tube/settings.py
- tube/utils/db.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- Add/fix SSL connection setup and unify connection definitions for Elasticsearch & PostgreSQL.
> Fix SSL configration for Elasticsearch & Postgres. Refactor Elasticsearch connections

- wait_for_quay.sh
Jira Ticket: [PXP-7936](https://ctds-planx.atlassian.net/browse/PXP-7936)
Fix wait_for_quay
[PXP-7936]: https://ctds-planx.atlassian.net/browse/PXP-7936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> correct sorting function of wait_for_quay

- tube/etl/indexers/base/parser.py
Jira Ticket: [MIDRC-458](https://ctds-planx.atlassian.net/browse/MIDRC-458)
fix data type of count of the field from index
[MIDRC-458]: https://ctds-planx.atlassian.net/browse/MIDRC-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(count): fix count of the field from index

- .github/workflows/integration_tests.yaml
Link to JIRA ticket if there is one:
> Use integration test workflow from .github repo

- tests/dataframe_tests/test_data/parent/etlMapping.yaml
- tests/dataframe_tests/test_parser.py
- tube/etl/indexers/aggregation/nested/parser.py
- tube/etl/indexers/base/parser.py
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/MIDRC-655
Fix boolean type in nested properties
> Fix es type

- .github/workflows/image_build_and_test.yaml
- .secrets.baseline
- Dockerfile
Link to JIRA ticket if there is one: 
- Remove unnecessary `version_data` logic
> Remove unnecessary version_data logic

- .github/workflows/image_build_and_test.yaml
- .secrets.baseline
Link to JIRA ticket if there is one:
> Update ubuntu version in GH Action workflow

- .github/workflows/integration_tests.yaml
Link to JIRA ticket if there is one: [GQE-472](https://ctds-planx.atlassian.net/browse/GQE-472)
[GQE-472]: https://ctds-planx.atlassian.net/browse/GQE-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Switch CI pipeline to helm based envs
